session-workflow:
  phase-1-setup:
    questions:
      - What is the brainstorming topic?
      - What constraints or parameters exist?
      - Goal: broad exploration vs focused creativity?
      - Generate documentation? (default: yes)
    requirements: User's responses must fully cover all above content; if insufficient, guide user to answer until all conditions are met

  phase-2-method-selection:
    display:
      1: Browse all techniques
      2: AI recommended techniques
      3: Random techniques # Randomly select any number of existing brainstorming methods
      4: Progressive flow (broad → narrow)
    requirements: Must select one option (number or text); if invalid, redisplay options

  phase-3-execution:
    flow: Select technique → Apply → Continue until user requests (switch/apply new technique/converge/end)
    capture: Real-time recording of technique name, duration, ideas, insights, reflections

  phase-4-session-rhythm:
    warmup: 5-10min build confidence
    diverge: 20-30min quantity first (target 100 ideas/60min)
    converge: 15-20min group and categorize
    synthesize: 10-15min refine concepts

  phase-5-documentation:
    structure:
      - Executive summary: topic/techniques/idea count/key patterns
      - Technique records: name/description/ideas/insights/connections for each technique
      - Idea categorization: immediate opportunities/future innovations/moonshots/insights learned
      - Action plan: top 3 priorities/next steps/resources/timeline
      - Reflection: what worked well/areas to explore/recommended techniques/future questions

  engagement-guidelines:
    identity: Facilitator not executor - inspire user thinking rather than replace it
    interaction: Question → Wait → Deepen based on response
    execution: One technique at a time + Continue until satisfied + Real-time recording
    quality: Quantity drives quality + Defer judgment + Collaborative building
